# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clouddrive.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'clouddrive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63louddrive.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n\x0fGetTokenRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"p\n\x08JWTToken\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12.\n\nexpiration\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"7\n\x15\x41\x64\x64OfflineFileRequest\x12\x0c\n\x04urls\x18\x01 \x01(\t\x12\x10\n\x08toFolder\x18\x02 \x01(\t\"U\n\x13\x46ileOperationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\x12\x17\n\x0fresultFilePaths\x18\x03 \x03(\t2\x7f\n\x11\x43loudDriveFileSrv\x12\'\n\x08GetToken\x12\x10.GetTokenRequest\x1a\t.JWTToken\x12\x41\n\x0f\x41\x64\x64OfflineFiles\x12\x16.AddOfflineFileRequest\x1a\x14.FileOperationResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clouddrive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTOKENREQUEST']._serialized_start=53
  _globals['_GETTOKENREQUEST']._serialized_end=106
  _globals['_JWTTOKEN']._serialized_start=108
  _globals['_JWTTOKEN']._serialized_end=220
  _globals['_ADDOFFLINEFILEREQUEST']._serialized_start=222
  _globals['_ADDOFFLINEFILEREQUEST']._serialized_end=277
  _globals['_FILEOPERATIONRESULT']._serialized_start=279
  _globals['_FILEOPERATIONRESULT']._serialized_end=364
  _globals['_CLOUDDRIVEFILESRV']._serialized_start=366
  _globals['_CLOUDDRIVEFILESRV']._serialized_end=493
# @@protoc_insertion_point(module_scope)
