# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.modules.downloadclient.cloudnas.clouddrive_pb2 as clouddrive__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in clouddrive_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudDriveFileSrvStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetToken = channel.unary_unary(
                '/CloudDriveFileSrv/GetToken',
                request_serializer=clouddrive__pb2.GetTokenRequest.SerializeToString,
                response_deserializer=clouddrive__pb2.JWTToken.FromString,
                _registered_method=True)
        self.AddOfflineFiles = channel.unary_unary(
                '/CloudDriveFileSrv/AddOfflineFiles',
                request_serializer=clouddrive__pb2.AddOfflineFileRequest.SerializeToString,
                response_deserializer=clouddrive__pb2.FileOperationResult.FromString,
                _registered_method=True)


class CloudDriveFileSrvServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddOfflineFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudDriveFileSrvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=clouddrive__pb2.GetTokenRequest.FromString,
                    response_serializer=clouddrive__pb2.JWTToken.SerializeToString,
            ),
            'AddOfflineFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOfflineFiles,
                    request_deserializer=clouddrive__pb2.AddOfflineFileRequest.FromString,
                    response_serializer=clouddrive__pb2.FileOperationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CloudDriveFileSrv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CloudDriveFileSrv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudDriveFileSrv(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CloudDriveFileSrv/GetToken',
            clouddrive__pb2.GetTokenRequest.SerializeToString,
            clouddrive__pb2.JWTToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddOfflineFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CloudDriveFileSrv/AddOfflineFiles',
            clouddrive__pb2.AddOfflineFileRequest.SerializeToString,
            clouddrive__pb2.FileOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
